import { StoreTemplateItem } from '../types';

export const STORE_ITEMS: StoreTemplateItem[] = [
  // PLANNERS
  {
    id: 'store-planner-2026',
    title: 'Planificador Anual Académico 2026/2027',
    category: 'planners',
    description: 'Agenda completa con vista mensual, semanal y diaria, seguimiento de hábitos y bloque de horarios de estudio.',
    paperTemplate: 'planner-weekly',
    coverColor: '#6366f1',
    coverStyle: 'academic',
    previewGradient: 'from-indigo-500 to-purple-600',
    tag: '⭐ Más Descargado',
    downloadsCount: 14200,
    rating: 4.9,
    isFreeAlways: true,
    features: ['Calendario interactivo', 'Control de tareas', 'Vista semanal en bloques', 'Sin caducidad'],
  },
  {
    id: 'store-planner-daily-zen',
    title: 'Daily Focus & Pomodoro Planner',
    category: 'planners',
    description: 'Planificador diario minimalista con bloques Pomodoro de 25 min, prioridades del día y cuadro de gratitud.',
    paperTemplate: 'planner-daily',
    coverColor: '#0d9488',
    coverStyle: 'minimal',
    previewGradient: 'from-teal-500 to-emerald-600',
    tag: 'Productividad',
    downloadsCount: 9800,
    rating: 4.8,
    isFreeAlways: true,
    features: ['Bloques de tiempo', 'Matriz urgente/importante', 'Notas rápidas'],
  },

  // NOTEBOOKS / APUNTES
  {
    id: 'store-cornell-pro',
    title: 'Plantilla Cornell Universitaria Pro',
    category: 'notebooks',
    description: 'Método Cornell oficial con columna izquierda para conceptos clave/preguntas, área de notas y bloque inferior de síntesis.',
    paperTemplate: 'cornell',
    coverColor: '#2563eb',
    coverStyle: 'cornell',
    previewGradient: 'from-blue-600 to-cyan-600',
    tag: 'Esencial Estudiante',
    downloadsCount: 28500,
    rating: 5.0,
    isFreeAlways: true,
    features: ['Estructura Cornell 100%', 'Margen de preguntas', 'Resumen final', 'Compatible con recortes'],
  },
  {
    id: 'store-grid-engineering',
    title: 'Cuaderno Milimetrado & Cuadrícula 5mm',
    category: 'notebooks',
    description: 'Ideal para matemáticas, física, ingeniería y dibujo técnico con cuadrícula milimétrica nítida en alta resolución.',
    paperTemplate: 'grid',
    coverColor: '#0284c7',
    coverStyle: 'engineering',
    previewGradient: 'from-cyan-600 to-blue-700',
    tag: 'Ingeniería & Matemáticas',
    downloadsCount: 16400,
    rating: 4.9,
    isFreeAlways: true,
    features: ['Cuadrícula 5x5mm', 'Líneas guía suaves', 'Alineación automática de reglas'],
  },
  {
    id: 'store-bullet-journal-dotted',
    title: 'Bullet Journal Dotted Aesthetic',
    category: 'notebooks',
    description: 'Papel punteado con puntos sutiles espaciados a 5mm. Perfecto para caligrafía, trackers y diagramas.',
    paperTemplate: 'dotted',
    coverColor: '#ec4899',
    coverStyle: 'aesthetic',
    previewGradient: 'from-pink-500 to-rose-600',
    tag: 'Aesthetic Pastel',
    downloadsCount: 22100,
    rating: 4.9,
    isFreeAlways: true,
    features: ['Puntos discretos 5mm', 'Modo libre para lettering', 'Fondo crema suave para la vista'],
  },
  {
    id: 'store-organic-hexagonal',
    title: 'Química Orgánica & Hexagonal Grid',
    category: 'notebooks',
    description: 'Papel con malla de anillos hexagonales de benceno para formulación química y bioquímica sin esfuerzo.',
    paperTemplate: 'hexagonal',
    coverColor: '#10b981',
    coverStyle: 'science',
    previewGradient: 'from-emerald-500 to-teal-700',
    tag: 'Ciencia & Medicina',
    downloadsCount: 11200,
    rating: 4.8,
    isFreeAlways: true,
    features: ['Hexágonos simétricos', 'Estructuras de Lewis', 'Anotación molecular'],
  },
  {
    id: 'store-music-sheet',
    title: 'Partituras y Pentagramas Clásicos',
    category: 'notebooks',
    description: 'Páginas con pentagramas musicales listos para composición, solfeo y anotación de notas.',
    paperTemplate: 'music',
    coverColor: '#78350f',
    coverStyle: 'classic',
    previewGradient: 'from-amber-700 to-yellow-900',
    tag: 'Música & Arte',
    downloadsCount: 6500,
    rating: 4.7,
    isFreeAlways: true,
    features: ['12 Pentagramas por página', 'Clave de sol y fa', 'Espaciado profesional'],
  },
  {
    id: 'store-dark-mode-grid',
    title: 'Dark Studio OLED Grid & Neon',
    category: 'notebooks',
    description: 'Papel negro ultra-oscuro para descansar la vista en sesiones nocturnas con soporte para tintas neón y pasteles.',
    paperTemplate: 'dark-grid',
    coverColor: '#09090b',
    coverStyle: 'dark',
    previewGradient: 'from-slate-900 via-gray-900 to-zinc-950',
    tag: 'Modo Noche OLED',
    downloadsCount: 18900,
    rating: 4.9,
    isFreeAlways: true,
    features: ['Fondo negro profundo', 'Cero fatiga visual', 'Resalta rotuladores neón'],
  },

  // STICKERS PACKS
  {
    id: 'store-stickers-study-pack',
    title: 'Pack Stickers: Estudio, Exámenes y Prioridades',
    category: 'stickers',
    description: 'Colección de más de 20 stickers digitales: banderas urgentes, sellos de A+, círculos de dudas y checks de repaso.',
    previewGradient: 'from-amber-400 to-orange-500',
    tag: 'Pack Completo',
    downloadsCount: 31200,
    rating: 5.0,
    isFreeAlways: true,
    features: ['Pegatinas transparentes', 'Arrastrables con un clic', 'Redimensionables'],
    stickers: [
      { emoji: '⭐', title: 'Destacado', category: 'General' },
      { emoji: '📌', title: 'Urgente', category: 'Prioridad' },
      { emoji: '🚨', title: 'Examen Importante', category: 'Estudio' },
      { emoji: '✅', title: 'Revisado', category: 'Check' },
      { emoji: '❓', title: 'Preguntar en Clase', category: 'Duda' },
      { emoji: '💡', title: 'Idea Clave', category: 'Concepto' },
      { emoji: '🎯', title: 'Objetivo', category: 'Meta' },
      { emoji: '💯', title: 'A+', category: 'Evaluación' },
      { emoji: '📖', title: 'Lectura Obligatoria', category: 'Estudio' },
      { emoji: '⏳', title: 'Pendiente', category: 'Tiempo' },
      { emoji: '🔥', title: 'Muy Frecuente', category: 'Tip' },
      { emoji: '🧠', title: 'Memorizar', category: 'Mnemotecnia' },
    ],
  },
  {
    id: 'store-stickers-aesthetic-tape',
    title: 'Pack Washi Tapes & Post-Its Pastel',
    category: 'stickers',
    description: 'Cintas decorativas washi tape, notas adhesivas estilo post-it pastel y clips para tus resúmenes aesthetic.',
    previewGradient: 'from-fuchsia-400 to-pink-500',
    tag: 'Aesthetic Planners',
    downloadsCount: 24700,
    rating: 4.9,
    isFreeAlways: true,
    features: ['Post-its pastel', 'Washi tapes coloridos', 'Decoración de apuntes'],
    stickers: [
      { emoji: '📝', title: 'Post-It Amarillo', category: 'Notas' },
      { emoji: '🏷️', title: 'Etiqueta Rosa', category: 'Tags' },
      { emoji: '📎', title: 'Clip de Papel', category: 'Clips' },
      { emoji: '🌸', title: 'Flor Sakura', category: 'Aesthetic' },
      { emoji: '☕', title: 'Café de Estudio', category: 'Chill' },
      { emoji: '🌿', title: 'Hoja Botánica', category: 'Aesthetic' },
      { emoji: '✨', title: 'Brillo Mágico', category: 'Deco' },
      { emoji: '🎨', title: 'Paleta Pastel', category: 'Deco' },
    ],
  },

  // COVERS / PORTADAS
  {
    id: 'store-cover-leather',
    title: 'Colección de Portadas Cuero Vintage & Clásico',
    category: 'covers',
    description: '6 Portadas elegantes texturizadas con lomo de encuadernación artesanal para cuadernos de honor.',
    coverColor: '#78350f',
    coverStyle: 'leather',
    previewGradient: 'from-amber-800 to-amber-950',
    tag: 'Elegancia Clásica',
    downloadsCount: 15300,
    rating: 4.8,
    isFreeAlways: true,
    features: ['Textura cuero italiano', 'Etiqueta dorada en relieve', 'Resistente'],
  },
  {
    id: 'store-cover-cyberpunk',
    title: 'Portadas Neón Cyberpunk & Dark Matrix',
    category: 'covers',
    description: 'Diseños oscuros con acentos neón cian y morado para cuadernos de programación, desarrollo y ciencia.',
    coverColor: '#0f172a',
    coverStyle: 'cyberpunk',
    previewGradient: 'from-cyan-500 via-indigo-600 to-purple-800',
    tag: 'Futurista',
    downloadsCount: 17800,
    rating: 4.9,
    isFreeAlways: true,
    features: ['Líneas de circuito luminosas', 'Estilo hacker / dev', 'Ultra contrast'],
  },
];
